name: 🎼 E2E Test

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      skip_tests:
        description: 'Comma-separated list of test to skip'
        required: false
        type: string
        default: ''

jobs:
  define-matrix:
    name: 📁 Define Test Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.filter.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📁 Generate lint matrix from JSON file
        id: filter
        uses: ./.github/actions/generate-matrix
        with:
          matrix_file_path: .github/workflows/matrix/e2e.json
          skip_keys: ${{ inputs.skip_tests }}

  test:
    name: ${{ matrix.title }}
    needs: define-matrix
    runs-on: macos-latest
    strategy:
      matrix: ${{ fromJson(needs.define-matrix.outputs.matrix) }}

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🔎 Detect changes
        uses: ./.github/actions/detect-changed/
        id: detect-changed
        with:
          files: ${{ toJson(matrix.files) }}

      - name: ⚙️ Project Setup
        if: steps.detect-changed.outputs.any_changed == 'true'
        uses: ./.github/actions/setup/
        with:
          docs: ${{ matrix.setup-docs }}
          playwright: ${{ matrix.setup-playwright }}
          pod: ${{ matrix.setup-pod }}
          ruby: ${{ matrix.setup-ruby }}

      - name: ${{ matrix.command_title }}
        if: steps.detect-changed.outputs.any_changed == 'true'
        run: ${{ matrix.command }}
