name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'README.md'
      - 'docs/**'
      - 'docs/**/*.js'
      - 'docs/**/*.mjs'
      - '.github/workflows/deploy_docs.yml'
  workflow_dispatch:

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/hydrogen'
          cache: 'npm'

      - name: Install project dependencies
        run: npm ci

      - name: Install docs dependencies
        run: npm run docs:clean-install

      - name: Add version info
        run: |
          echo "DEPLOY_DATE=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
          echo "const deployInfo = {date:'${{ env.DEPLOY_DATE }}',commit:'${{ github.sha }}'};" > docs/src/deploy-info.js

      - name: Build docs
        run: npm run docs:build

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build

  deploy:
    name: Deploy to GitHub Pages
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
