name: Linting

on: pull_request
jobs:
  prettier:
    name: Lint Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/hydrogen'

      - name: Install project dependencies
        run: npm ci

      - name: Lint Prettier
        run: npm run prettier:check
  eslint:
    name: Lint ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/hydrogen'

      - name: Install project dependencies
        run: npm ci

      - name: Lint ESLint
        run: npm run eslint:check
  typescript:
    name: Lint types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/hydrogen'

      - name: Install project dependencies
        run: npm ci

      - name: Install docs dependencies
        run: npm run docs:clean-install

      - name: Lint types
        run: npm run type:check
  comitlint:
    name: Lint commit messages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/hydrogen'

      - name: Install project dependencies
        run: npm ci

      - name: Lint commit messages
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
